name: inspector

services:
  api:
    build:
      context: .
    container_name: ${COMPOSE_PROJECT_NAME}-api
    command: pnpm run start:prod
    restart: always
    networks:
      - default

networks:
  default:
    driver: bridge
